version: "3"
services:
  client:
    build: ./client/
    ports:
      - "3000:3000"
    networks:
      - crud-app
    volumes:
      - ./client/:/usr/src/app
    depends_on:
      - server
  server:
    build: ./server/
    ports:
      - "4000:4000"
    networks:
      - crud-app
    volumes:
      - ./server/:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - crud-app
    volumes:
      - mongo-data:/data/db

networks:
  crud-app:
    driver: bridge

volumes:
  mongo-data:
    driver: local